allow to checkout specific Pi-hole repository revision
chubchubsancho/ansible-pi-hole pull request #5
Opened 2022-01-31 21:34 UTC by mrtwnklr

Adds the variable `pi_hole_version`.
This variable defines a specific git repository revision to allow a stable/repeatable installation of Pi-hole.
Defaults to value `master` so current behavior of role is unchanged.

- [x] Successfully tested on a clean Debian 11 installation
- [x] README.md updated

2022-01-31 22:37 UTC, chubchubsancho commented
Hi @mrtwnklr,
Nice feature I need to fix molecule test before merging. 
I hope have time to do it tomorrow.

2022-01-31 22:38 UTC, chubchubsancho approved these changes

2022-02-01 21:31 UTC, chubchubsancho commented
It seems that specify a specific tag does not work.
`pi-hole` installation script try to update git repository as we are not on a branch but on tag this cannot be done and result an installation failure.
`update_repo` function is located here https://github.com/pi-hole/pi-hole/blob/875ad04fde48cd4855d7048f87e50de6e72df0fe/automated%20install/basic-install.sh#L497-L531

and failure is return by https://github.com/pi-hole/pi-hole/blob/875ad04fde48cd4855d7048f87e50de6e72df0fe/automated%20install/basic-install.sh#L517 which return
``` 
You are not currently on a branch.
Please specify which branch you want to merge with.
```

2022-02-01 21:33 UTC, chubchubsancho commented
As i've no more credit on `travisCI` you can manually run molecule test on your side by launching 
```
docker run --rm -it --env image=ubuntu --env version=20.04 --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD") -v /var/run/docker.sock:/var/run/docker.sock -w /tmp/$(basename "$PWD") quay.io/ansible/toolset:3.5.0 molecule test
```

I need to take some time in order to move to another CI

2022-02-01 21:35 UTC, chubchubsancho requested changes
Specifying a specific release tag won't work

2022-02-01 21:58 UTC, mrtwnklr commented
> Specifying a specific release tag won't work

I will take a look at it.

2022-02-01 22:11 UTC, mrtwnklr commented
Well, my reason for pinning a specific version of Pi-hole was not academic but because installing `master` with your role did not work on my machine (with the current state of the official repository).
This is confirmed by your test suite.

Try to change `defaults/main.yml` to

```yaml
---
# Revision of Pi-hole repository
pi_hole_version: "v5.8.1"
```
and run your mentioned molecule test statement again.

For me this run is successful:

```bash
PLAY RECAP *********************************************************************
instance                   : ok=12   changed=7    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

[...]

PLAY RECAP *********************************************************************
instance                   : ok=7    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0

INFO     Idempotence completed successfully.
INFO     Pruning extra files from scenario ephemeral directory
```

2022-02-02 06:04 UTC, mrtwnklr commented
I have currently only small time windows for analysis so this could take a while.

- [/] Installing from `master` works fine when `pi_hole_install_dir` is not set to /etc/.pihole

2022-02-02 06:24 UTC, mrtwnklr commented
With commit https://github.com/pi-hole/pi-hole/commit/95150a5d8568700efd00e80e100c67a3e2bead24 the Pi-hole installer takes 20 commits when cloning.

- [x] Installing from `master` works fine when changing `git.depth` from 1 to 20 in `install.yml`
- [x] Installing from tag `v5.0` works fine when changing `git.depth` from 1 to 20 in `install.yml` and `pi_hole_version` to `v5.0`

Do you want to have this fix (1 -> 20) included in this PR or do you prefer a dedicated PR?

2022-02-02 15:01 UTC, mrtwnklr commented
Pi-hole `basic-install.sh` failed because `git pull` is executed without revision. If in detached state (tag is checked out) the revision is taken from `.git/config`.

When cloning a repository without `--depth` fetch config looks like:

```ini
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
```

When cloning with `--depth` fetch config is conrete:

```ini
remote.origin.fetch=+refs/heads/v5.0:refs/remotes/origin/v5.0
```

So, while we do not need to specify `--depth` when cloning a branch, we need it when cloning a tag.

That's why I decided to align the arguments for git clone to the ones of the official pi-hole basic-install script: `HEAD` instead of `master` and `--depth 20`. By the way: using `HEAD` now could prevent a future bug, should Pi-hole project decide one day to rename `master` to `main`.

2022-02-02 15:42 UTC, chubchubsancho commented
Hi @mrtwnklr thanks for your debug :ok_hand: 
`depth` was removed from code in PR #7

 You can re add `depth` in this PR

2022-02-02 20:07 UTC, mrtwnklr commented
> Hi @mrtwnklr thanks for your debug ok_hand `depth` was removed from code in PR #7

:handshake: 

> You can re add `depth` in this PR

I've already done it with https://github.com/chubchubsancho/ansible-pi-hole/pull/5/commits/ec49d95b9b0289e844299a8a5c837b29ef168a61 .

2022-02-02 20:19 UTC, chubchubsancho approved these changes
Nice job @mrtwnklr

2022-02-02 20:20 UTC, merged